### ISSUE TITLE
3rd party launcher availability

### ISSUE THREAD

**Issue by ghost** [MrMelon54/better-resource-pack-sorting-fabric#1]
Hi,
This mod cannot be automatically downloaded via third-party launchers (such as PolyMC). Could you enable it in CurseForge's project page?

**Comment by mrmelon54** [comment]
I am now releasing on modrinth instead starting with 1.19 if you need older version just comment below and I will backport eventually. I've basically had enough of curseforge lol.

**Comment by ghost** [comment]
Understandable, thanks!
