### ISSUE TITLE
Crash 1.19.3

### ISSUE THREAD

**Issue by Arthurmeade12** [MrMelon54/better-resource-pack-sorting-fabric#2]
Seems like the mixin failed to apply. As to why, I have no idea, since I am not a developer. 
[Crash log](https://mclo.gs/SHWRbdC)

Thank you for any help.

**Comment by mrmelon54** [comment]
Looks like it just don't properly support 1.19.3 probably due to vanilla code changes. I'll fix it eventually.

**Comment by mrmelon54** [comment]
Report on https://github.com/mrmelon54/better_resource_pack_sorting if this issue still occurs in 1.20
